#!/usr/bin/env bash
# authelia — pre-startup init: mint the initial file-backend user database.
#
# Authelia's file backend needs a valid users_database.yml with an argon2id-hashed
# password before it will start. We can't hash at template-render time (no hashing
# tool in the render path), so we generate it here using the authelia image's own
# `crypto hash` CLI, seeded from EXIST_USERNAME / EXIST_PASSWORD / EXIST_EMAIL.
#
# Idempotent, no sentinel: if users_database.yml already exists we leave it (and any
# extra users / rotated passwords) alone. To add or rotate users later:
#   docker exec -it authelia authelia crypto hash generate argon2 --password '<pw>'
# then edit hosting/authelia/users_database.yml.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Host-only: needs docker to run the authelia hashing CLI. Nothing to do in adhoc.
[[ "${IN_CONTAINER:-}" == "1" ]] && exit 0

USERS="$SCRIPT_DIR/users_database.yml"
if [[ -f "$USERS" ]]; then
    echo "[authelia] users_database.yml present — skipping."
    exit 0
fi

ENV_SHARED="$SCRIPT_DIR/../../.env.shared"
get() { grep -E "^$1=" "$ENV_SHARED" 2>/dev/null | head -1 | cut -d= -f2-; }
USERNAME="$(get EXIST_USERNAME)"; USERNAME="${USERNAME:-admin}"
EMAIL="$(get EXIST_EMAIL)";       EMAIL="${EMAIL:-admin@${USERNAME}.local}"
PASSWORD="$(get EXIST_PASSWORD)"

# Keep in sync with the image: line in docker-compose.exist.yml.
IMAGE="authelia/authelia:4.39.5"

if [[ -z "$PASSWORD" ]]; then
    echo "[authelia] EXIST_PASSWORD is not set in .env.shared — run ./existential.sh first." >&2
    exit 1
fi
if ! command -v docker >/dev/null 2>&1; then
    echo "[authelia] docker is required to hash the initial password." >&2
    exit 1
fi

echo "[authelia] Generating initial user '$USERNAME' (argon2id) ..."
HASH="$(docker run --rm --entrypoint authelia "$IMAGE" \
            crypto hash generate argon2 --password "$PASSWORD" \
        | sed -n 's/^Digest: //p')"

if [[ -z "$HASH" ]]; then
    echo "[authelia] Failed to generate password hash (is the image tag '$IMAGE' valid?)." >&2
    exit 1
fi

umask 077
cat > "$USERS" <<YAML
# Generated by exist.initial.sh — argon2id hash of EXIST_PASSWORD. Gitignored.
# Add/rotate users with: docker exec -it authelia authelia crypto hash generate argon2 --password '<pw>'
users:
  ${USERNAME}:
    disabled: false
    displayname: "${USERNAME}"
    password: "${HASH}"
    email: "${EMAIL}"
    groups:
      - admins
YAML

echo "[authelia] Wrote $USERS (user: $USERNAME)."
