services:
  decree:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./daemon/.decree:/work/.decree:z
      - notes_data:/notes_data
      - dropbox_data:/dropbox_data:z
      - ./rclone:/config/rclone:z
    environment:
      - DECREE_AI=${DECREE_AI}
      - DECREE_DAEMON=true
      - DECREE_INTERVAL=2
      - NTFY_TOKEN=${NTFY_TOKEN}
      - NTFY_URL=${NTFY_URL}
      - DECREE_NOTES_DIR=${DECREE_NOTES_DIR}
      - DROPBOX_DEST_DIR=${DROPBOX_DEST_DIR}
      - IN_CONTAINER=1
    tty: false
    # networks:
    #   - exist

volumes:
  notes_data:
  dropbox_data:

networks:
  exist:
    external: true
