services:
  linkwarden-pg:
    container_name: linkwarden-pg
    image: postgres:16-alpine
    restart: unless-stopped
    networks:
      - exist
    environment: 
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: ${LINKWARDEN_POSTGRES_PASSWORD}
      POSTGRES_USER: ${LINKWARDEN_POSTGRES_USER}
    volumes:
      - linkwarden_pg_data:/var/lib/postgresql/data

  linkwarden:
    container_name: linkwarden
    image: ghcr.io/linkwarden/linkwarden:latest # comment to build from source
    environment:
      - DATABASE_URL=postgresql://${LINKWARDEN_POSTGRES_USER}:${LINKWARDEN_POSTGRES_PASSWORD}@linkwarden-pg:5432/postgres
      - LINKWARDEN_NEXTAUTH_URL=http://192.168.44.191:44200/api/v1/auth
      - NEXTAUTH_SECRET=${LINKWARDEN_NEXTAUTH_SECRET}
    restart: always
    networks:
      - exist
    ports:
      - 44200:3000
    volumes:
      - linkwarden_data:/data/data
    depends_on:
      - linkwarden-pg
      - linkwarden-meilisearch

  linkwarden-meilisearch:
    container_name: linkwarden-meilisearch
    image: getmeili/meilisearch:v1.12.8
    restart: always
    networks:
      - exist
    environment:
      - MEILI_MASTER_KEY=${LINKWARDEN_MEILI_MASTER_KEY}
    volumes:
      - linkwarden_meili_data:/meili_data

volumes:
  linkwarden_data: # linkwarden_data dataset will need to be created in TrueNAS
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${TRUENAS_SERVER_ADDRESS},nolock,soft,rw,nfsvers=4"
      device: ":${TRUENAS_CONTAINER_PATH}/linkwarden_data"

  linkwarden_pg_data: # linkwarden_pg_data dataset will need to be created in TrueNAS
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${TRUENAS_SERVER_ADDRESS},nolock,soft,rw,nfsvers=4"
      device: ":${TRUENAS_CONTAINER_PATH}/linkwarden_pg_data"

  linkwarden_meili_data: # linkwarden_meili_data dataset will need to be created in TrueNAS
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${TRUENAS_SERVER_ADDRESS},nolock,soft,rw,nfsvers=4"
      device: ":${TRUENAS_CONTAINER_PATH}/linkwarden_meili_data"

networks:
  exist:
    external: true
