import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * The sidebar is written by hand, not autogenerated from the folder tree.
 *
 * The point is to lead with flows — what the system does — and push the
 * per-service catalog down into Reference, where you go when something
 * specific is broken. Autogenerating from `.` would surface ~45 app pages
 * as the primary navigation, which is the sprawl this structure exists to
 * hide.
 *
 * Each Reference subsection still autogenerates from its folder, so adding a
 * service page requires no change here. Adding a *flow* likewise just needs a
 * file in docs/flows/.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    'getting-started',
    'how-it-works',
    {
      type: 'category',
      label: 'Flows',
      link: {type: 'doc', id: 'flows/index'},
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'flows'}],
    },
    'build-on-it',
    {
      type: 'category',
      label: 'Reference',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Services',
          link: {type: 'doc', id: 'services/index'},
          items: [{type: 'autogenerated', dirName: 'services'}],
        },
        {
          type: 'category',
          label: 'AI',
          link: {type: 'doc', id: 'ai/index'},
          items: [{type: 'autogenerated', dirName: 'ai'}],
        },
        {
          type: 'category',
          label: 'Storage',
          link: {type: 'doc', id: 'storage/index'},
          items: [{type: 'autogenerated', dirName: 'storage'}],
        },
        {
          type: 'category',
          label: 'Hosting',
          link: {type: 'doc', id: 'hosting/index'},
          items: [{type: 'autogenerated', dirName: 'hosting'}],
        },
        {
          type: 'category',
          label: 'Integrations',
          link: {type: 'doc', id: 'integrations/index'},
          items: [{type: 'autogenerated', dirName: 'integrations'}],
        },
        {
          type: 'category',
          label: 'Automation Engine',
          items: [{type: 'autogenerated', dirName: 'decree'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'Alternatives',
      link: {type: 'doc', id: 'graveyard/index'},
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'graveyard'}],
    },
    'licensing',
    'open-source-notices',
  ],
};

export default sidebars;
