services:
  appsmith:
    container_name: appsmith
    image: index.docker.io/appsmith/appsmith-ce
    restart: unless-stopped
    networks:
      - exist
    ports:
      # - "80:80"
      - "44080:80"
    volumes:
      - appsmith_data:/appsmith-stacks

  # nuke:
  #   image: node:24-alpine
  #   entrypoint: >
  #     sh -c '
  #       sleep 500
  #     '
  #   restart: "no"
  #   volumes:
  #     - appsmith_data:/appsmith-stacks

  appsmith-decree:
    container_name: appsmith-decree
    build:
      context: ../../automations
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - exist
    environment:
      - DECREE_DAEMON=true
      - DECREE_INTERVAL=2
      - IN_CONTAINER=1
      - EXIST_BACKUP_RCLONE_REMOTE=${EXIST_BACKUP_RCLONE_REMOTE}
    volumes:
      - ./decree:/work/.decree:z
      - ../../automations/shared_routines:/work/.decree/shared_routines:ro,z
      - ../../automations/lib:/work/.decree/lib:ro,z
      - ../../automations/runs:/work/.decree/runs:z
      - ../../automations/secrets:/secrets:ro,z
      - appsmith_data:/volumes/appsmith_data
    tty: false

volumes:
  appsmith_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${EXIST_NFS_SERVER_ADDRESS},nolock,soft,rw,nfsvers=4"
      device: ":${EXIST_NFS_BASE_PATH}/appsmith_data"

networks:
  exist:
    external: true
