services:
  api:
    image: ghcr.io/shirsakm/nightlio-api:0.1.1
    restart: unless-stopped
    environment:
      - SECRET_KEY=${NIGHTLIO_SECRET_KEY}
      - JWT_SECRET=${NIGHTLIO_JWT_SECRET}
      - CORS_ORIGINS=${NIGHTLIO_CORS_ORIGINS}
      - ENABLE_GOOGLE_OAUTH=${NIGHTLIO_ENABLE_GOOGLE_OAUTH}
      - DEFAULT_SELF_HOST_ID=${NIGHTLIO_USERNAME}
      - DATABASE_PATH=/app/data/nightlio.db
      - PORT=5000
    volumes:
      - ./data:/app/data
    networks:
      - exist

  web:
    image: ghcr.io/shirsakm/nightlio-frontend:0.1.1
    restart: unless-stopped
    depends_on: [api]
    ports:
      - "5173:80"  # or put behind your own reverse proxy with TLS
    networks:
      - exist

networks:
  exist:
    external: true
