commands:
  ai_router: opencode run {prompt}
  ai_interactive: opencode
max_retries: 3
max_depth: 10
max_log_size: 2097152
default_routine: develop
hooks:
  beforeAll: ''
  afterAll: ''
  beforeEach: ''
  afterEach: ''
routines:
  develop:
    enabled: true
  notes/compile-notes:
    enabled: true
  notes/generate-index:
    enabled: true
  notes/sync-dropbox:
    enabled: true
  notes/sync-nextcloud:
    enabled: true
  notify:
    enabled: true
