commands:
  ai_router: opencode run {prompt}
  ai_interactive: opencode
max_retries: 3
max_depth: 10
max_log_size: 2097152
default_routine: develop
routine_source: ../routines
hooks:
  beforeAll: ""
  afterAll: ""
  beforeEach: ""
  afterEach: ""
shared_routines:
  develop:
    enabled: true
  notes/compile-notes:
    enabled: false
  notes/generate-index:
    enabled: false
  notes/sync-dropbox:
    enabled: false
  notes/sync-nextcloud:
    enabled: false
  notify:
    enabled: true
