#!/usr/bin/env bash
# render-templates.sh — process *.exist.* template files inside existential-adhoc.
# Run via: run_adhoc env REPO_DIR=/repo bash /src/templates.sh
#
# A rendered destination is written ONCE and skipped thereafter — that is what
# preserves user edits and prompted answers. There is deliberately no override:
# the old --force overwrote with no undo and never said what it would touch.
# `./existential.sh reset` archives the rendered files instead, so the next run
# re-renders from a clean tree with everything recoverable.
set -euo pipefail

REPO_DIR="${REPO_DIR:-/repo}"

# Shared service-enablement + env helpers read $SCRIPT_DIR as the repo root;
# here that is REPO_DIR. Provides SERVICE_CATEGORIES, _load_env_shared,
# _reload_env_shared, _enable_var_for, service_is_enabled, _find_service_dirs.
SCRIPT_DIR="${REPO_DIR}"

# Normally /src (the adhoc container's mount). reset.sh sources this file on the
# HOST to reuse _template_to_dst, where /src does not exist — so fall back to the
# repo's own src/ rather than dying under `set -e` on the first source.
_SRC_DIR=/src
[[ -d "$_SRC_DIR" ]] || _SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# shellcheck source=src/utils/generate_password.sh
. "${_SRC_DIR}/utils/generate_password.sh"
# shellcheck source=src/utils/generate_hex_key.sh
. "${_SRC_DIR}/utils/generate_hex_key.sh"
# shellcheck source=src/utils/service-common.sh
. "${_SRC_DIR}/utils/service-common.sh"

# ── Generators ────────────────────────────────────────────────────────────────

gen_password() { generate_24_char_password; }
gen_hex()      { generate_hex_key "${1:-32}"; }

# ── Placeholder replacement ───────────────────────────────────────────────────

# Render a template entirely in memory: read the source, resolve every placeholder
# (EXIST_* references, generated secrets, interactive EXIST_CLI prompts) in a string
# variable, and print the finished content to stdout. Nothing is written to disk
# here — the caller writes the destination once, after this returns. Interactive
# prompts go to the terminal (stderr); only the resolved file lands on stdout.
render_template() {
    local src="$1" dst="$2"
    local content; content="$(cat "$src")"
    local line_num val

    # docker-compose files: leave ${EXIST_*} and ${SLUG_*} as live references.
    # Docker Compose resolves them from the root .env (generated by generate-compose.ts
    # by merging .env.shared + all service .env files). Baking them here means a token
    # rotation would require a reset + re-render + restart; leaving them as references means
    # only the root .env needs to be regenerated.
    local _is_compose=false
    [[ "$(basename "$dst")" == docker-compose*.yml ]] && _is_compose=true

    # EXIST_* — substitute values already written to .env.shared.
    # Skip when rendering .env.shared itself (would replace keys with their own values).
    # Skip for docker-compose files (see above).
    if [[ -f "${REPO_DIR}/.env.shared" && "$dst" != "${REPO_DIR}/.env.shared" && "$_is_compose" != "true" ]]; then
        local key value _escaped k
        local -a _keys=()
        local -A _vals=()
        while IFS='=' read -r key value || [[ -n "$key" ]]; do
            [[ "$key" =~ ^EXIST_ ]] || continue
            # A blank value still substitutes — as the empty string. Skipping it
            # (the old `-n "$value"` guard) left the literal token in the rendered
            # file, so a shared key the user had not filled in shipped the string
            # "EXIST_MINIO_SERVER_URL" into a container as if it were a URL. That
            # crash-looped minio, blanked nextcloud's trusted domain, and rendered
            # EXIST_USERNAME as a postgres role name. Empty is the honest render of
            # an empty value; a leftover placeholder is never what the caller meant.
            [[ -n "$key" ]] || continue
            _keys+=("$key")
            _vals["$key"]="$value"
        done < "${REPO_DIR}/.env.shared"

        # Build the substitutions longest-key-first so a shorter key (EXIST_FOO)
        # can't rewrite the prefix of a longer one (EXIST_FOOBAR). The bare-token
        # form is anchored on a trailing word boundary (\b) for the same reason and
        # so a key name embedded in unrelated text can't be silently replaced with
        # a secret value.
        local -a sed_args=()
        if [[ ${#_keys[@]} -gt 0 ]]; then
            while IFS= read -r k; do
                _escaped="${_vals[$k]//\\/\\\\}"
                _escaped="${_escaped//&/\\&}"
                _escaped="${_escaped//|/\\|}"
                sed_args+=(-e "s|\\\${${k}[^}]*}|${_escaped}|g" -e "s|${k}\\b|${_escaped}|g")
            done < <(printf '%s\n' "${_keys[@]}" | awk '{ print length, $0 }' | sort -rn | cut -d' ' -f2-)
        fi
        if [[ ${#sed_args[@]} -gt 0 ]]; then
            content="$(sed "${sed_args[@]}" <<<"$content")"
        fi
    fi

    # Service-local .env — substitute ${VAR} references from the rendered .env
    # in the same service directory. Only the ${VAR} form is used (not bare-word)
    # to avoid accidentally matching YAML keys or other prose.
    # .env.exist sorts before docker-compose.exist.yml, so .env is already written
    # by the time the compose template is processed in the same directory.
    # Skip for docker-compose files: service vars are in the root .env at runtime.
    local _svc_env; _svc_env="$(dirname "$src")/.env"
    if [[ -f "$_svc_env" && "$dst" != "$_svc_env" && "$_is_compose" != "true" ]]; then
        local _sk _sv _sescaped _sk2
        local -a _skeys=() _ssed_args=()
        local -A _svals=()
        while IFS='=' read -r _sk _sv || [[ -n "$_sk" ]]; do
            [[ "$_sk" =~ ^[[:space:]]*# ]] && continue
            [[ -n "$_sk" ]] || continue
            _skeys+=("$_sk")
            _svals["$_sk"]="${_sv:-}"
        done < "$_svc_env"
        if [[ ${#_skeys[@]} -gt 0 ]]; then
            while IFS= read -r _sk2; do
                _sescaped="${_svals[$_sk2]//\\/\\\\}"
                _sescaped="${_sescaped//&/\\&}"
                _sescaped="${_sescaped//|/\\|}"
                _ssed_args+=(-e "s|\\\${${_sk2}[^}]*}|${_sescaped}|g")
            done < <(printf '%s\n' "${_skeys[@]}" | awk '{ print length, $0 }' | sort -rn | cut -d' ' -f2-)
        fi
        if [[ ${#_ssed_args[@]} -gt 0 ]]; then
            content="$(sed "${_ssed_args[@]}" <<<"$content")"
        fi
    fi

    # Auto-generated — one replacement at a time so each occurrence gets a unique value
    while grep -q "EXIST_24_CHAR_PASSWORD" <<<"$content"; do
        line_num=$(grep -n "EXIST_24_CHAR_PASSWORD" <<<"$content" | head -1 | cut -d: -f1)
        val=$(gen_password 24)
        content="$(sed "${line_num}s|EXIST_24_CHAR_PASSWORD|${val}|" <<<"$content")"
    done
    while grep -q "EXIST_32_CHAR_HEX_KEY" <<<"$content"; do
        line_num=$(grep -n "EXIST_32_CHAR_HEX_KEY" <<<"$content" | head -1 | cut -d: -f1)
        val=$(gen_hex 32)
        content="$(sed "${line_num}s|EXIST_32_CHAR_HEX_KEY|${val}|" <<<"$content")"
    done

    # EXIST_CLI — read text prompt.
    # Shows the contiguous comment block directly above the field as context.
    # If that block contains `# DEFAULT_FROM: EXIST_FOO`, the value of EXIST_FOO
    # (already resolved above) is used as the default when the user enters nothing.
    while grep -q "EXIST_CLI" <<<"$content"; do
        local match line_content key_name block_start prev_line context
        local default_from default_val escaped
        match=$(grep -n "EXIST_CLI" <<<"$content" | head -1)
        line_num="${match%%:*}"
        line_content="${match#*:}"
        key_name="${line_content%%=*}"

        block_start=$(( line_num - 1 ))
        while (( block_start >= 1 )); do
            prev_line=$(sed -n "${block_start}p" <<<"$content")
            [[ "$prev_line" =~ ^[[:space:]]*# ]] || break
            block_start=$(( block_start - 1 ))
        done
        block_start=$(( block_start + 1 ))

        if (( block_start < line_num )); then
            context=$(sed -n "${block_start},$((line_num - 1))p" <<<"$content")
        else
            context=""
        fi

        default_from=$(printf '%s\n' "$context" | \
            sed -n 's/^# *DEFAULT_FROM: *\([A-Z_][A-Z0-9_]*\) *$/\1/p' | head -1)
        default_val=""
        if [[ -n "$default_from" ]]; then
            default_val=$(grep -E "^${default_from}=" <<<"$content" | head -1 | cut -d= -f2-)
        fi

        # When re-rendering an existing file (an _ALWAYS_RENDER destination),
        # recover the current value
        # from the destination by extracting what was previously substituted at
        # this line position. Matches both key=VALUE and bare-token (e.g. YAML
        # volume) contexts. Current value takes priority over DEFAULT_FROM.
        if [[ -e "$dst" ]]; then
            local _tpl_line _before_cli _after_cli _dst_line _stripped _current_val
            _tpl_line=$(sed -n "${line_num}p" <<<"$content")
            _before_cli="${_tpl_line%%EXIST_CLI*}"
            _after_cli="${_tpl_line#*EXIST_CLI}"
            _dst_line=$(sed -n "${line_num}p" "$dst" 2>/dev/null || true)
            if [[ -n "$_dst_line" && "$_dst_line" == "${_before_cli}"*"${_after_cli}" ]]; then
                _stripped="${_dst_line#"$_before_cli"}"
                _current_val="${_stripped%"$_after_cli"}"
                if [[ -n "$_current_val" ]]; then default_val="$_current_val"; fi
            fi
        fi

        # Prompt on the controlling terminal. We use /dev/tty directly so the
        # prompt works even inside $() command substitution (where [[ -t 0 ]] is
        # unreliable under docker compose run -it). /dev/tty is the process's
        # controlling terminal; if none exists (non-interactive, -T container) the
        # redirect fails and we fall through.
        # Guard: if stdin is explicitly /dev/null (/proc/$BASHPID/fd/0 resolves to
        # it), the caller signalled non-interactive mode. /dev/tty is still
        # accessible in test contexts and would otherwise bypass </dev/null and block.
        local _stdin_fd; _stdin_fd=$(readlink "/proc/$BASHPID/fd/0" 2>/dev/null || true)
        if [[ "$_stdin_fd" != "/dev/null" ]]; then
            printf '\n' >&2
            if [[ -n "$context" ]]; then printf '%s\n' "$context" >&2; fi
            if { true >/dev/tty; } 2>/dev/null; then
                printf '  %s [%s]: ' "${key_name}" "${default_val}" >/dev/tty
                IFS= read -r val </dev/tty || val="${default_val}"
            elif [[ -t 0 ]]; then
                read -rp "  ${key_name} [${default_val}]: " val || val="${default_val}"
            else
                val="${default_val}"
            fi
        else
            val="${default_val}"
        fi
        if [[ -z "$val" ]]; then val="${default_val}"; fi

        escaped="${val//\\/\\\\}"
        escaped="${escaped//&/\\&}"
        escaped="${escaped//|/\\|}"
        content="$(sed "${line_num}s|EXIST_CLI|${escaped}|" <<<"$content")"
    done

    # EXIST_HOST_IP — the LAN address of the machine running the stack.
    #
    # This used to be an EXIST_CLI prompt, which is a question the code can
    # answer: existential.sh detects it (`ip route get 1.1.1.1`) and passes it in
    # as EXIST_DETECTED_HOST_IP. Detection has to happen out there, on the host —
    # in here we are inside the adhoc container, where that same command returns
    # the container's address.
    #
    # Resolved BEFORE the EXIST_NIP_DOMAIN loop below, which reads the
    # EXIST_LOCAL_HOST_IP line back out of the content it has already
    # substituted. A blank IP at this point is what used to send EXIST_DOMAIN to
    # x.internal on a first run.
    while grep -q "EXIST_HOST_IP" <<<"$content"; do
        line_num=$(grep -n "EXIST_HOST_IP" <<<"$content" | head -1 | cut -d: -f1)
        val="${EXIST_DETECTED_HOST_IP:-}"
        [[ "$val" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]] || val=""
        content="$(sed "${line_num}s|EXIST_HOST_IP|${val}|" <<<"$content")"
    done

    # EXIST_NIP_DOMAIN — a wildcard-DNS domain derived from the host's LAN IP.
    # nip.io resolves 192-168-1-50.nip.io -> 192.168.1.50 from public DNS, so
    # `<slug>.<domain>` works on every device with no pihole and no /etc/hosts.
    # Resolved after the EXIST_CLI loop so EXIST_LOCAL_HOST_IP is already filled
    # in; it must appear ABOVE this token in the template for that to hold.
    # Falls back to x.internal (pihole-resolved) when no usable IP is known.
    while grep -q "EXIST_NIP_DOMAIN" <<<"$content"; do
        line_num=$(grep -n "EXIST_NIP_DOMAIN" <<<"$content" | head -1 | cut -d: -f1)
        _nip_ip=$(sed -n 's/^EXIST_LOCAL_HOST_IP=\(.*\)$/\1/p' <<<"$content" | head -1)
        if [[ "$_nip_ip" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            val="${_nip_ip//./-}.nip.io"
        else
            val="x.internal"
        fi
        content="$(sed "${line_num}s|EXIST_NIP_DOMAIN|${val}|" <<<"$content")"
    done

    printf '%s\n' "$content"
}

# ── Template processing ───────────────────────────────────────────────────────

_template_to_dst() {
    local dir fname before after
    dir="$(dirname "$1")"; fname="$(basename "$1")"
    if [[ "$fname" == *".exist."* ]]; then
        before="${fname%%.exist.*}"; after="${fname##*.exist.}"
        if [[ "${before,,}" == "${after,,}" ]]; then echo "${dir}/${before}"
        else echo "${dir}/${before}.${after}"
        fi
    elif [[ "$fname" == *".exist" ]]; then
        echo "${dir}/${fname%.exist}"
    fi
}

_STATS_CREATED=0
_STATS_SKIPPED=0
_STATS_REGENERATED=0

# ── Always-render destinations ────────────────────────────────────────────────
#
# Rendered files are normally written once and then skipped (see
# _process_one_template) so a user's edits survive. These are the exceptions:
# regenerated on EVERY run, and never hand-edited.
#
# A destination only qualifies when its render is a pure function of
# (template + .env.shared) — no secrets, no EXIST_CLI prompts — so re-running can
# never lose information. _assert_always_render_safe enforces that.
#
# To customise one, the user flips the EXIST_KEEP line in the stamped header to
# true. That claims the file: it is theirs from then on and is never rewritten.
# See _render_opted_out.
_ALWAYS_RENDER=(
    "services/dashy/dashy-conf.yml"
    "ai/honcho/config.toml"
)

# True when $1 (an absolute destination path) is in _ALWAYS_RENDER.
_renders_always() {
    local rel="${1#"$REPO_DIR/"}" entry
    for entry in "${_ALWAYS_RENDER[@]}"; do
        [[ "$rel" == "$entry" ]] && return 0
    done
    return 1
}

# An always-render destination is overwritten with no backup, so anything the
# user could not reproduce from the template must not live there. Interactive
# answers (EXIST_CLI) and generated secrets are exactly that: EXIST_CLI would
# re-prompt on every run, and a fresh secret each run would break whatever
# already consumed the old one. Fail loudly rather than silently churn.
_assert_always_render_safe() {
    local src="$1" dst="$2" tok f

    # Directory templates are cp -r'd, which copies *into* an existing
    # destination rather than replacing it — the second run would nest. Only
    # regular files can be always-rendered.
    if [[ -d "$src" ]]; then
        echo "ERROR: ${dst#"$REPO_DIR/"} is in _ALWAYS_RENDER but its template is a" >&2
        echo "       directory. Only regular files can be always-rendered." >&2
        exit 1
    fi

    # EXIST_DOMAIN and other plain .env.shared lookups stay allowed; only prompts
    # and generated secrets are rejected.
    for tok in EXIST_CLI EXIST_24_CHAR_PASSWORD EXIST_32_CHAR_HEX_KEY; do
        if grep -q "$tok" "$src" 2>/dev/null; then
            echo "ERROR: ${dst#"$REPO_DIR/"} is in _ALWAYS_RENDER but its template" >&2
            echo "       ($(basename "$src")) contains ${tok}." >&2
            echo "       Always-rendered files are overwritten every run with no backup," >&2
            echo "       so they must not carry prompts or generated secrets." >&2
            echo "       fix: drop it from _ALWAYS_RENDER in src/templates.sh, or move" >&2
            echo "            the ${tok} value into .env.shared and reference it." >&2
            exit 1
        fi
    done
}

# Rendered files that hold secrets (DB passwords, API keys, private keys) must
# not be world/group-readable. chmod 600 anything that looks like a credential
# file so a fresh render never leaves secrets at the default umask (664/644).
_secure_if_secret() {
    local f="$1" base; base="$(basename "$f")"
    case "$base" in
        .env|.env.*|*.pem|*_password*.txt) chmod 600 "$f" 2>/dev/null || true ;;
        # Rendered config files carry bearer tokens (decree-webhook) and daemon
        # credentials (decree). Everything reaching this function was just
        # rendered from a *.exist.* template, so both spellings are in scope —
        # ai/chatterbox renders config.yaml, not config.yml.
        config.yml|*-config.yml|config.yaml|*-config.yaml) chmod 600 "$f" 2>/dev/null || true ;;
    esac
}

# Marker line stamped at the top of every always-rendered file. check-drift.ts
# keys off this string to skip these destinations, so the policy lives in exactly
# one place — don't reword it without updating src/test/unit/check-drift.ts.
_GENERATED_MARKER="DO NOT EDIT — regenerated on every ./existential.sh run"

# True when the user has claimed an existing always-rendered destination by
# flipping the EXIST_KEEP line in its header to true. The file is then theirs:
# we never rewrite it again, so their edits survive every subsequent run.
#
# The toggle is a *comment*, not a bare token, so it stays valid in whatever
# format the destination is — an uncommented marker would be a syntax error in
# the YAML that dashy has to parse. Only the header is inspected, so the same
# words appearing later in the file mean nothing.
_render_opted_out() {
    local dst="$1"
    [[ -f "$dst" ]] || return 1
    head -20 "$dst" 2>/dev/null | grep -qE '^[[:space:]]*#[[:space:]]*EXIST_KEEP:[[:space:]]*true[[:space:]]*$'
}

# Print the finished always-render content for $dst: the header, then the
# rendered template. The header carries the opt-out switch a user flips to claim
# the file — see _render_opted_out.
_compose_always_render() {
    local src="$1" rendered="$2"
    local _rel_src="${src#"$REPO_DIR/"}"

    printf '%s\n' \
        "# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" \
        "# ${_GENERATED_MARKER}" \
        "# Base: ${_rel_src}" \
        "#" \
        "# Want to customise this file? Change the next line to true." \
        "# It then belongs to you and is never regenerated again." \
        "# EXIST_KEEP: false" \
        "# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
    printf '%s\n' "$rendered"
}

_process_one_template() {
    local src="$1" dst
    dst="$(_template_to_dst "$src")"

    # .env files are user-owned once rendered — never overwrite. `reset` archives
    # them instead, so the secrets inside stay recoverable.
    # This guard stays first: it wins over _ALWAYS_RENDER too.
    local _dstbase; _dstbase="$(basename "$dst")"
    if [[ -e "$dst" ]] && [[ "$_dstbase" == .env || "$_dstbase" == .env.* ]]; then
        return 1
    fi

    local _always=false
    if _renders_always "$dst"; then
        # The user claimed this file by flipping EXIST_KEEP to true — it is
        # theirs now, so it falls back to the ordinary write-once behaviour.
        # Checked before the safety assertion:
        # a claimed file is nobody's business but the user's.
        if _render_opted_out "$dst"; then
            return 1
        fi
        _always=true
        _assert_always_render_safe "$src" "$dst"
    fi

    # Render-once: an existing destination is left alone unless it is in
    # _ALWAYS_RENDER (a pure function of template + .env.shared, so rewriting it
    # can lose nothing). To re-render everything, run `./existential.sh reset`.
    if [[ -e "$dst" ]] && [[ "$_always" != "true" ]]; then
        return 1
    fi

    if [[ -d "$src" ]]; then
        cp -r "$src" "$dst"
        local f rendered
        while IFS= read -r f; do
            # Checked explicitly: the call sites use `|| _rc=$?`, which disables
            # set -e for this whole function, so an unchecked failure here would
            # write an empty string over $f and still report success.
            if ! rendered="$(render_template "$f" "$f")"; then
                echo "ERROR: failed to render ${f#"$REPO_DIR/"}" >&2
                exit 1
            fi
            printf '%s\n' "$rendered" > "$f"
            _secure_if_secret "$f"
        done < <(find "$dst" -type f 2>/dev/null)
    else
        # Resolve every placeholder in memory, then write the destination once.
        # If the user aborts mid-prompt, render_template never returns, so the
        # destination is never written and can't hold a literal EXIST_CLI token.
        #
        # Both assignments below are status-checked rather than left to set -e:
        # the call sites invoke this function as `… || _rc=$?`, which disables
        # set -e for the entire body. An unchecked failure would leave $rendered
        # empty, and the `>` on the next line would then truncate a live
        # single-file bind mount to nothing while still reporting "regenerated".
        local rendered
        if ! rendered="$(render_template "$src" "$dst")"; then
            echo "ERROR: failed to render ${src#"$REPO_DIR/"}" >&2
            exit 1
        fi
        if [[ "$_always" == "true" ]]; then
            if ! rendered="$(_compose_always_render "$src" "$rendered")"; then
                echo "ERROR: failed to compose ${dst#"$REPO_DIR/"} — left unchanged." >&2
                exit 1
            fi
        fi
        # `>` truncates the existing inode in place. That is required, not
        # incidental: an always-rendered file may be a *single-file* bind mount
        # (dashy-conf.yml is), and replacing it via mv/rename would swap the inode
        # and detach the running container's mount. Never adopt the
        # archive-then-rename pattern generate-compose.ts uses for the root
        # compose file here.
        printf '%s\n' "$rendered" > "$dst"
        _secure_if_secret "$dst"
        # Every volume becomes a host bind mount in generate-compose.ts
        # from each service's x-exist-volumes block: ${EXIST_NFS_HOST_MOUNT}/<name> for nfs-marked
        # volumes when a host mount is set, else volumes/<name>/. The top-level
        # volumes: block here is just the declaration source it reads.
    fi

    if [[ "$_always" == "true" ]]; then
        echo "  regenerated: ${dst#"$REPO_DIR/"}"
        return 2
    fi

    echo "  created: ${dst#"$REPO_DIR/"}"
    return 0
}

# Tally one _process_one_template result: 0 created, 2 regenerated, else skipped.
_tally() {
    case "$1" in
        0) _STATS_CREATED=$(( _STATS_CREATED + 1 )) ;;
        2) _STATS_REGENERATED=$(( _STATS_REGENERATED + 1 )) ;;
        *) _STATS_SKIPPED=$(( _STATS_SKIPPED + 1 )) ;;
    esac
}

_process_templates_in() {
    local root="$1"; [[ -d "$root" ]] || return 0
    local _rc

    while IFS= read -r src; do
        _rc=0; _process_one_template "$src" || _rc=$?
        _tally "$_rc"
    done < <(find "$root" -name '*.exist.*' -type d \
        -not -path '*/graveyard/*' -not -path '*/.git/*' \
        -not -path '*/node_modules/*' -not -path '*/site/*' 2>/dev/null | sort)

    while IFS= read -r src; do
        _rc=0; _process_one_template "$src" || _rc=$?
        _tally "$_rc"
    done < <(find "$root" \( -name '*.exist.*' -o -name '*.env.exist' \) -type f \
        -not -path '*/graveyard/*' -not -path '*/.git/*' \
        -not -path '*/node_modules/*' -not -path '*/site/*' 2>/dev/null | sort)
}

# ── Main ──────────────────────────────────────────────────────────────────────
# Guarded so the file can be sourced (e.g. by src/test/unit/test-templates.sh) to load
# the functions without rendering anything. Runs only when executed directly.

_main() {
    if [[ -f "${REPO_DIR}/.env.exist.shared" ]]; then
        local _rc=0
        _process_one_template "${REPO_DIR}/.env.exist.shared" || _rc=$?
        _tally "$_rc"
        if [[ "$_rc" == 0 ]]; then _reload_env_shared; fi
    fi
    _load_env_shared

    while IFS= read -r svc_dir; do
        if service_is_enabled "$svc_dir"; then
            _process_templates_in "$svc_dir"
        fi
    done < <(_find_service_dirs)

    echo "Created ${_STATS_CREATED} file(s), regenerated ${_STATS_REGENERATED}, skipped ${_STATS_SKIPPED} existing"
    if [[ "$_STATS_SKIPPED" -gt 0 ]]; then
        echo "  (existing files are left alone — ./existential.sh reset archives them"
        echo "   to archive/<timestamp>/ so the next run renders fresh)"
    fi
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    _main
fi
