#!/usr/bin/env bash
# openviking — pre-startup init: write ov.conf into the data volume.
#
# Runs on the host (needs no container tooling). Called every `./existential.sh run`;
# skips silently if ov.conf already exists — delete it to regenerate.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

if [[ "${IN_CONTAINER:-}" == "1" ]]; then
    exit 0
fi

# shellcheck source=.env
source "${SCRIPT_DIR}/.env"

# existential.sh exports .env.shared before running initials; source it anyway so
# `./existential.sh run openviking` works on its own. The endpoint comes from the
# EMBED role, not the global one: embeddings are a small model under high call
# volume, so they are the first thing worth moving to a second box.
if [[ -f "${REPO_ROOT}/.env.shared" ]]; then
    set -a
    # shellcheck disable=SC1091
    source "${REPO_ROOT}/.env.shared"
    set +a
fi
# shellcheck source=../../src/utils/model-endpoints.sh
source "${REPO_ROOT}/src/utils/model-endpoints.sh"
OLLAMA_URL="$(endpoint_for embed)"

# ── Automation output directory ───────────────────────────────────────────────
# workspace/ at the repo root is the knowledgebase: the same tree hermes and
# code-server share, so everything you work on is indexed without a second
# directory to keep in step. It is a plain host directory, not a declared volume
# — human-facing content, so it stays out of volumes/.
#
# generate-compose.ts already creates workspace/ (ensureBindSource) on a full
# run, but `./existential.sh run openviking` skips that, so create it here too,
# along with the ai/ subdirectory the agent automations write into. The README is
# seeded only when absent — this is the user's directory, not ours.
WORKSPACE_DIR="${REPO_ROOT}/workspace"
mkdir -p "${WORKSPACE_DIR}/ai"
if [[ ! -e "${WORKSPACE_DIR}/ai/README.md" ]]; then
    cat > "${WORKSPACE_DIR}/ai/README.md" << 'AIEOF'
# workspace/ai/ — automation output

The agent automations write here. Everything in this directory was generated by
a routine, not by you, so treat it as output: read it, move what is worth keeping
somewhere else, delete the rest.

Two rules make this directory work, and they pull in opposite directions on
purpose:

- It **is** indexed into OpenViking, along with the rest of `workspace/`. Past
  output is searchable, so an agent can find and build on what an earlier run
  produced.
- It **is not** synced to MinIO. The `workspace-sync` routine excludes it, so
  nothing written here fires a storage event. That is the one thing standing
  between this setup and an infinite loop of runs triggering runs.

If you move a file out of here into the rest of `workspace/`, it becomes a
normal workspace file: synced, and able to trigger matches like any other.

This directory is gitignored. Delete this README once you have your bearings —
nothing regenerates it while it exists, and nothing depends on it.
AIEOF
    echo "[openviking] workspace/ai/ output directory created."
fi

# Activate the indexer cron. cron/ is gitignored (it is the user's active set),
# so the tracked example is the only copy in git — this just puts it in place so
# indexing works from the first `docker compose up -d` rather than after a manual
# cp. Guarded on absence: edit or delete the active copy and it stays that way.
CRON_SRC="${SCRIPT_DIR}/decree/cron.example/openviking-index-knowledgebase.md"
CRON_DST="${SCRIPT_DIR}/decree/cron/openviking-index-knowledgebase.md"
if [[ -f "${CRON_SRC}" && ! -e "${CRON_DST}" ]]; then
    mkdir -p "$(dirname "${CRON_DST}")"
    cp "${CRON_SRC}" "${CRON_DST}"
    echo "[openviking] knowledgebase indexer cron activated."
fi

DATA_DIR="${REPO_ROOT}/volumes/openviking_data"
mkdir -p "${DATA_DIR}"

CONF="${DATA_DIR}/ov.conf"
if [[ -f "${CONF}" ]]; then
    # ov.conf is the user's once written — except for the embedding endpoint,
    # which is EXIST_OLLAMA_URL's to own. Without this, moving ollama to another
    # host leaves openviking retrying a dead address, and the only symptom is
    # "Failed to generate embedding: Connection error" deep in its logs.
    have_base=$(grep -m1 '"api_base"' "${CONF}" \
        | sed -E 's/.*"api_base"[[:space:]]*:[[:space:]]*"([^"]*)".*/\1/' || true)
    if [[ "${have_base}" == "${OLLAMA_URL}/v1" ]]; then
        echo "[openviking] ov.conf exists — skipping (delete to regenerate)."
    elif [[ "${have_base}" =~ ^https?://[^/]+:11434(/v1)?$ ]]; then
        echo "[openviking] ov.conf api_base=${have_base} but EXIST_OLLAMA_URL=${OLLAMA_URL} — reconciling."
        sed -i -E "s#\"api_base\"[[:space:]]*:[[:space:]]*\"[^\"]*\"#\"api_base\": \"${OLLAMA_URL}/v1\"#" "${CONF}"
    else
        echo "[openviking] ov.conf api_base=${have_base} (not an ollama endpoint) — leaving it alone."
    fi
    exit 0
fi

cat > "${CONF}" << EOF
{
  "embedding": {
    "dense": {
      "provider": "ollama",
      "api_key": "local",
      "api_base": "${OLLAMA_URL}/v1",
      "model": "${OPENVIKING_EMBEDDING_MODEL}",
      "dimension": ${OPENVIKING_EMBEDDING_DIM}
    }
  },
  "storage": {
    "workspace": "/app/.openviking/data"
  },
  "server": {
    "host": "0.0.0.0",
    "port": 1933,
    "auth_mode": "api_key",
    "root_api_key": "${OPENVIKING_API_KEY}",
    "cors_origins": ["*"]
  },
  "memory": {
    "version": "v2"
  }
}
EOF

echo "[openviking] ov.conf written."
