services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      # - 40800:8000
      - 49443:9443
    volumes:
      # For Docker
      # - /var/run/docker.sock:/var/run/docker.sock
      # For Podman
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock:z
      - portainer_data:/data
      - ./portainer_password.txt:/shared/portainer_password.txt:Z
    security_opt:
      - label=disable
    networks:
      - exist
    restart: unless-stopped
    command: >
      -H unix:///var/run/docker.sock
      --admin-password-file /shared/portainer_password.txt

  portainer-decree:
    container_name: portainer-decree
    build:
      context: ../../automations
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - exist
    environment:
      - DECREE_DAEMON=true
      - DECREE_INTERVAL=2
      - IN_CONTAINER=1
      - EXIST_BACKUP_RCLONE_REMOTE=${EXIST_BACKUP_RCLONE_REMOTE}
    volumes:
      - ./decree:/work/.decree:z
      - ../../automations/shared_routines:/work/.decree/shared_routines:ro,z
      - ../../automations/lib:/work/.decree/lib:ro,z
      - ../../automations/runs:/work/.decree/runs:z
      - ../../automations/secrets:/secrets:ro,z
      - portainer_data:/volumes/portainer_data
    tty: false

volumes:
  portainer_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=${EXIST_NFS_SERVER_ADDRESS},nolock,soft,rw,nfsvers=4"
      device: ":${EXIST_NFS_BASE_PATH}/portainer_data"

networks:
  exist:
    external: true