services:
  redis:
    container_name: redis
    image: redis:alpine
    user: "${EXIST_PUID:-1000}:${EXIST_PGID:-1000}"
    restart: unless-stopped
    networks:
      - exist
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass ${REDIS_PASSWORD}
    # ports:
    #   - "6379:6379"
    volumes:
      - ./redis_data:/data:Z

networks:
  exist:
    external: true
